#ifndef OPENSSL_NO_ERR
#include <openssl/err.h>
#ifndef OPENSSL_NO_TPRSA
#include <openssl/tprsa.h>


static ERR_STRING_DATA TPRSA_str_functs[] = {
    {ERR_PACK(ERR_LIB_TPRSA, TPRSA_F_TPRSA_PRIVATE_ENCRYPT, 0), "TPRSA_private_encrypt"},
    {ERR_PACK(ERR_LIB_TPRSA, TPRSA_F_TPRSA_PRIVATE_DECRYPT, 0), "TPRSA_private_decrypt"},
    {ERR_PACK(ERR_LIB_TPRSA, TPRSA_F_TPRSA_GENERATE_SHA1, 0), "TPRSA_generate_sha1"},
    {ERR_PACK(ERR_LIB_TPRSA, TPRSA_F_TPRSA_PRIVATE_DECRYPT, 0), "TPRSA_private_decrypt"},
    {ERR_PACK(ERR_LIB_TPRSA, TPRSA_F_TPRSA_PRIVATE_FINALLY_DECRYPT, 0), "TPRSA_private_finally_decrypt"},
    {ERR_PACK(ERR_LIB_TPRSA, TPRSA_F_TPRSA_PAILLIER_L, 0), "TPRSA_paillier_l"},
    {ERR_PACK(ERR_LIB_TPRSA, TPRSA_F_TPRSA_GENERATE_CONTINUOUS_PRIMES, 0), "TPRSA_Generate_Continuous_Primes"},
    {ERR_PACK(ERR_LIB_TPRSA, TPRSA_F_TPRSA_PAILLIER_KEY_GENERATE, 0), "TPRSA_Paillier_Key_Generate"},
    {ERR_PACK(ERR_LIB_TPRSA, TPRSA_F_TPRSA_PAILLIER_ENC_MESSAGE, 0), "TPRSA_Paillier_Enc_Message"},
    {ERR_PACK(ERR_LIB_TPRSA, TPRSA_F_TPRSA_PAILLIER_DEC_CIPHERTEXT, 0), "TPRSA_Paillier_Dec_Ciphertext"},
    {ERR_PACK(ERR_LIB_TPRSA, TPRSA_F_TPRSA_CLIENT_NEW, 0), "TPRSA_CLIENT_new"},
    {ERR_PACK(ERR_LIB_TPRSA, TPRSA_F_TPRSA_CLIENT_SET_T_PHI, 0), "TPRSA_CLIENT_Set_t_phi"},
    {ERR_PACK(ERR_LIB_TPRSA, TPRSA_F_TPRSA_CLIENT_SET_PRIMES_ARRAY, 0), "TPRSA_CLIENT_Set_Primes_Array"},
    {ERR_PACK(ERR_LIB_TPRSA, TPRSA_F_TPRSA_CLIENT_SET_PKP, 0), "TPRSA_CLIENT_Set_pkP"},
    {ERR_PACK(ERR_LIB_TPRSA, TPRSA_F_TPRSA_CLIENT_SET_PA, 0), "TPRSA_CLIENT_Set_pa"},
    {ERR_PACK(ERR_LIB_TPRSA, TPRSA_F_TPRSA_CLIENT_SET_QA, 0), "TPRSA_CLIENT_Set_qa"},
    {ERR_PACK(ERR_LIB_TPRSA, TPRSA_F_TPRSA_CLIENT_CHECK_V, 0), "TPRSA_CLIENT_Check_v"},
    {ERR_PACK(ERR_LIB_TPRSA, TPRSA_F_TPRSA_CLIENT_COMPUTER_CTP, 0), "TPRSA_CLIENT_Computer_ctp"},
    {ERR_PACK(ERR_LIB_TPRSA, TPRSA_F_TPRSA_CLIENT_COMPUTER_CTQ, 0), "TPRSA_CLIENT_Computer_ctq"},
    {ERR_PACK(ERR_LIB_TPRSA, TPRSA_F_TPRSA_CLIENT_PKP_ENC_MULT_TWO, 0), "TPRSA_CLIENT_PkP_ENC_MULT_TWO"},
    {ERR_PACK(ERR_LIB_TPRSA, TPRSA_F_TPRSA_CLIENT_COM_CN, 0), "TPRSA_CLIENT_COM_CN"},
    {ERR_PACK(ERR_LIB_TPRSA, TPRSA_F_TPRSA_CLIENT_SET_N, 0), "TPRSA_CLIENT_Set_n"},
    {ERR_PACK(ERR_LIB_TPRSA, TPRSA_F_TPRSA_CLIENT_SET_E, 0), "TPRSA_CLIENT_Set_e"},
    {ERR_PACK(ERR_LIB_TPRSA, TPRSA_F_TPRSA_CLIENT_GET_RANDOM, 0), "TPRSA_CLIENT_Get_Random"},
    {ERR_PACK(ERR_LIB_TPRSA, TPRSA_F_TPRSA_CLIENT_GET_RANDOM_RANGE, 0), "TPRSA_CLIENT_Get_Random_Range"},
    {ERR_PACK(ERR_LIB_TPRSA, TPRSA_F_TPRSA_CLIENT_COM_EPHINA, 0), "TPRSA_CLIENT_COM_EPHINA"},
    {ERR_PACK(ERR_LIB_TPRSA, TPRSA_F_TPRSA_CLIENT_COM_C_MPHIN, 0), "TPRSA_CLIENT_COM_C_MPHIN"},
    {ERR_PACK(ERR_LIB_TPRSA, TPRSA_F_TPRSA_CLIENT_COM_CR3, 0), "TPRSA_CLIENT_COM_Cr3"},
    {ERR_PACK(ERR_LIB_TPRSA, TPRSA_F_TPRSA_CLIENT_COM_CS, 0), "TPRSA_CLIENT_COM_Cs"},
    {ERR_PACK(ERR_LIB_TPRSA, TPRSA_F_TPRSA_SERVER_SET_PAILLIER_KEY, 0), "TPRSA_SERVER_Set_Paillier_Key"},
    {ERR_PACK(ERR_LIB_TPRSA, TPRSA_F_TPRSA_SERVER_SET_T_PHI, 0), "TPRSA_SERVER_SET_t_phi"},
    {ERR_PACK(ERR_LIB_TPRSA, TPRSA_F_TPRSA_SERVER_SET_PRIMES_ARRAY, 0), "TPRSA_SERVER_Set_Primes_Array"},
    {ERR_PACK(ERR_LIB_TPRSA, TPRSA_F_TPRSA_SERVER_SET_PS, 0), "TPRSA_SERVER_Set_ps"},
    {ERR_PACK(ERR_LIB_TPRSA, TPRSA_F_TPRSA_SERVER_SET_QS, 0), "TPRSA_SERVER_SET_qs"},
    {ERR_PACK(ERR_LIB_TPRSA, TPRSA_F_TPRSA_SERVER_SET_PKP, 0), "TPRSA_SERVER_Set_pkP"},
    {ERR_PACK(ERR_LIB_TPRSA, TPRSA_F_TPRSA_SERVER_GET_RANDOM, 0), "TPRSA_SERVER_Get_Random"},
    {ERR_PACK(ERR_LIB_TPRSA, TPRSA_F_TPRSA_SERVER_COMPUTE_E_PHI_S_E_PHI_PS, 0), "TPRSA_SERVER_COMPUTE_E_PHI_S_E_PHI_PS"},    
    {ERR_PACK(ERR_LIB_TPRSA, TPRSA_F_TPRSA_SERVER_COMPUTE_E_PHI_S_E_PHI_QS, 0), "TPRSA_SERVER_COMPUTE_E_PHI_S_E_PHI_QS"},
    {ERR_PACK(ERR_LIB_TPRSA, TPRSA_F_TPRSA_SERVER_DEC_COM_N, 0), "TPRSA_SERVER_DEC_COM_N"},
    {ERR_PACK(ERR_LIB_TPRSA, TPRSA_F_TPRSA_SERVER_COM_EPHINS, 0), "TPRSA_SERVER_COM_EPHINS"},
    {ERR_PACK(ERR_LIB_TPRSA, TPRSA_F_TPRSA_SERVER_SET_E, 0), "TPRSA_SERVER_SET_E"},
    {ERR_PACK(ERR_LIB_TPRSA, TPRSA_F_TPRSA_SERVER_COM_CETAS, 0), "TPRSA_SERVER_COM_CETAS"},
    {ERR_PACK(ERR_LIB_TPRSA, TPRSA_F_SERVER_COM_C_RHO_S, 0), "SERVER_COM_C_RHO_S"},
    {ERR_PACK(ERR_LIB_TPRSA, TPRSA_F_TPRSA_SERVER_COM_DS, 0), "TPRSA_SERVER_COM_DS"},
    {ERR_PACK(ERR_LIB_TPRSA, TPRSA_F_TPRSA_KEY_GEN, 0), "TPRSA_KEY_GEN"},
    {ERR_PACK(ERR_LIB_TPRSA, TPRSA_F_TPRSA_DEALER_TRSK, 0), "TPRSA_DEALER_TRSK"},
    {ERR_PACK(ERR_LIB_TPRSA, TPRSA_F_TPRSA_DEALER_NEW, 0), "TPRSA_DEALER_NEW"},
    {ERR_PACK(ERR_LIB_TPRSA, TPRSA_F_TPRSA_SERVER_SET_DS, 0), "TPRSA_SERVER_SET_DS"},
    {ERR_PACK(ERR_LIB_TPRSA, TRRAS_F_TPRSA_SERVER_SET_N, 0), "TPRSA_SERVER_SET_N"},
    {ERR_PACK(ERR_LIB_TPRSA, TPRSA_F_TPRSA_CLIENT_SET0_E, 0), "TPRSA_CLIENT_SET0_E"},
    {ERR_PACK(ERR_LIB_TPRSA, TPRSA_F_TPRSA_COLLABORATE_SIGN, 0), "TPRSA_COLLABORATE_SIGN"},
    {ERR_PACK(ERR_LIB_TPRSA, TPRSA_F_TPRSA_PRE_CRT, 0), "TPRSA_PRE_CRT"},
    {ERR_PACK(ERR_LIB_TPRSA, TPRSA_F_TPRSA_SERVER_NEW, 0), "TPRSA_SERVER_NEW"},
    {ERR_PACK(ERR_LIB_TPRSA, TPRSA_F_TPRSA_SERVER_PRECOMPILED, 0), "TPRSA_SERVER_PRECOMPILED"},
    {ERR_PACK(ERR_LIB_TPRSA, TPRSA_F_TPRSA_CLIENT_PRECOMPILED, 0), "TPRSA_CLIENT_PRECOMPILED"},
    {ERR_PACK(ERR_LIB_TPRSA, TPRSA_F_TPRSA_CLIENT_SET_DA, 0), "TPRSA_CLIENT_SET_DA"},

};


static ERR_STRING_DATA TPRSA_str_reasons[] = {
    {ERR_PACK(ERR_LIB_TPRSA, 0, ERR_R_MALLOC_FAILURE), "malloc failure"},
    {ERR_PACK(ERR_LIB_TPRSA, 0, TPRSA_R_GENERATE_SHA1_FAILED), "invalid input"},
    {ERR_PACK(ERR_LIB_TPRSA, 0, TPRSA_R_PARAMS_NULL_ERROR), "invalid params"}

};



int ERR_load_TPRSA_strings(void)
{
#ifndef OPENSSL_NO_ERR
    if (ERR_func_error_string(TPRSA_str_functs[0].error) == NULL)
    {
        ERR_load_strings(0, TPRSA_str_functs);
        ERR_load_strings(0, TPRSA_str_reasons);
    }
#endif
    return 1;
}
#endif
#endif